### ISSUE TITLE
CLOSE_WEBTRANSPORT_SESSION capsule clarification

### ISSUE THREAD

**Issue by martenrichter** [ietf-wg-webtrans/draft-ietf-webtrans-http2#106]
Thanks for adding the CLOSE_WEBTRANSPORT_SESSION capsule,
https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/pull/104 .
I have read 
`An endpoint that sends a CLOSE_WEBTRANSPORT_SESSION capsule MUST set the FIN bit
on the frame carrying the capsule. The recipient MUST close the stream upon
receipt of the capsule.`
Now I wonder if a capsule must always be inside one Http2 frame.

I use node.js as a base and their streams.
Up to now, I have sent a capsule using multiple writes to the http/2 stream, which may lead to multiple Http/2 frames or not (sorry, I have not read the HTTP/2 in much detail so far). The reason is that I can avoid one memcopy.

Do you know if this is legal per spec?

Or is it sufficient that a capsule may come through multiple frames? and that only the last part of the CLOSE_WEBTRANSPORT_SESSION  is in a frame with the fin bit (I hope node.js sets this when using end).

**Comment by DavidSchinazi** [comment]
The HTTP/2 framing layer is allowed to split data streams at any point. The boundaries of HTTP/2 DATA frames don't carry any semantics, only the reassembled stream. So a capsule can definitely end up split into multiple HTTP/2 DATA frames.

I'm not familiar with the Node.js implementation, it could create one HTTP/2 DATA frame for each write, or it could keep an internal buffer, or something else entirely.

So you're right that this text could be improved. I'll also note that HTTP/2 uses an END_STREAM flag, not a FIN bit (FIN bit is used by HTTP/3) so this sentence is definitely wrong.

I would perhaps replace it with `An endpoint that sends a CLOSE_WEBTRANSPORT_SESSION capsule MUST then close the stream. The recipient MUST close the stream upon receipt of the capsule.`

**Comment by martenrichter** [comment]
Thanks, so I can leave it as it is. If node.js split the frames or not, I actually do not know, I tried to trace it down in their source code, but from just reading it is not so clear. I believe it joins some writes, but I do not know for sure.

**Comment by ekinnear** [comment]
That new text looks good to me, thanks David! I do think you can leave the current implementation as-is, as long as the last bit of the data goes out on the wire with END_STREAM set, it doesn't really matter what the framing boundaries end up being.
(Indeed, this was imported from H3 and would need to be updated to use END_STREAM.)

I'm not sure it's worth having a lot of discussion to say "needs to set END_STREAM on the final frame that gets generated" vs. just saying "needs to close", since that's in practice what people using H2 libraries will be doing.

**Comment by martenrichter** [comment]
Thanks. I think "need to close" is enough. I was confused about whether I had gotten something conceptually wrong about the capsule protocol and H2 webtransport, as it sounded more like H3. So far, I am (or my lib) only talking to myself, so I am not sure if I got everything right.
