### ISSUE TITLE
Minor changes required for Subprotocol Negotiation headers

### ISSUE THREAD

**Issue by AnkshitJain** [ietf-wg-webtrans/draft-ietf-webtrans-http2#114]
[Subprotocol Negotiation headers](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http2/draft-ietf-webtrans-http2.html#section-3.4-3) references [HTTP3](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http2/draft-ietf-webtrans-http2.html#HTTP3) in Section 3.4-3. This should be [WEBTRANSPORT-H3](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http2/draft-ietf-webtrans-http2.html#WEBTRANSPORT-H3). 

Additionally, the listed headers, `WebTransport-Subprotocols-Available` and `WebTransport-Subprotocol`, are out of date with the headers in the [WEBTRANSPORT-H3 draft 10](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-10#name-subprotocol-negotiation), which are `WT-Available-Protocols` and `WT-Protocol`.

**Comment by ekinnear** [comment]
Thank you! Updating to resync with WT-H3, and great catch on the reference.
