### ISSUE TITLE
Document how MAX_DATA interacts with the enclosing HTTP/2 flow control scheme?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http2#27]
Document how MAX_DATA interacts with the enclosing HTTP/2 flow control scheme

_Originally posted by @afrind in https://github.com/ietf-wg-webtrans/draft-webtransport-http2/pull/26#discussion_r736000396_

**Comment by ekinnear** [comment]
I tend to think we might want to have a section entirely on flow control since we've now got several layers: 

- HTTP/2 connection level
- HTTP/2 stream for the CONNECT stream
- WT_MAX_DATA for the WT session
    - Noting that this is different than the HTTP/2 layer's CONNECT stream, since we want to be able to indicate the sum of stream data separately from other control frames
- WT_MAX_STREAM_DATA for each WT stream

And stream-count flow control
- HTTP/2 stream limits don't really apply once you've got the WT session up
- WT_MAX_STREAMS limits stream counts within a WT session

Just indicating the intended usage of each of these knobs would be helpful.

**Comment by ekinnear** [comment]
(From #30: Since QUIC's flow control credits work differently from H2, it may be worth explicitly stating how this works here.)

**Comment by DavidSchinazi** [comment]
Chair notes from IETF 112 meeting: no one objected to proposal of resolving this by documenting how flow control works and pitfalls

**Comment by vasilvv** [comment]
Why do we need WT_MAX_DATA in first place?  I thought that since we have flow control from the HTTP/2 side, we don't need it.

**Comment by ekinnear** [comment]
> Why do we need WT_MAX_DATA in first place

We want to be able to say "don't send me any more data on this stream" while still allowing control frames on that stream
