### ISSUE TITLE
Defaults for newly created sessions

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-ietf-webtrans-http2#71]
A newly created session can be used for control data (WT_MAX_STREAMS, etc...) and datagrams, but it can't be used for reliable application data.  This is because the initial limits for streams is zero and the initial limits for stream data (both session-level and stream-level limits) is also zero.

We might consider setting baseline defaults for sessions.  These would likely need to be small because there would be no way to retract any value that was set in a default.  That is, if we set a stream limit of 10 (for any type of stream), then all implementations would be required to accept 10 streams.

If we go this way, we might use HTTP/2 stream limit defaults as a guide.  For stream data limits at least, we might allow 64k of data (the HTTP/2 default for [SETTINGS_INITIAL_WINDOW_SIZE](https://datatracker.ietf.org/doc/html/rfc9113#section-6.5.2-2.8.1)) relying on the same reasoning as HTTP/2 (which wasn't that thoroughly reasoned, to be honest, but whatever).  We cannot use that approach for stream limits as HTTP/2 sets an unlimited default, which doesn't work with the style of limiting we use.  Also, stream limits are independent of any HTTP/2 resources needed for tracking streams, so that would not apply.

Alternatively, we might use the current value of the HTTP/2 stream limits.  That is, the value of [SETTINGS_INITIAL_WINDOW_SIZE](https://datatracker.ietf.org/doc/html/rfc9113#section-6.5.2-2.8.1) might be input to a function that determines session- and stream-level limits.  This might also work if [SETTINGS_MAX_CONCURRENT_STREAMS](https://datatracker.ietf.org/doc/html/rfc9113#section-6.5.2-2.6.1) is set, but we might need a cap otherwise.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, this will need WG discussion at IETF 116

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 116, consensus in room was to not use default values and instead communicate numbers. We'll discuss how to communicate this (settings, headers, both, etc.) at a future time.

**Comment by DavidSchinazi** [comment]
Chair: discussed again at IETF 116 at the end of the session. Consensus in room was to not use default values and instead communicate numbers with settings. The setting default value is zero. If an intermediary doesn't know what limits backends accept, it can not send the setting.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, see discussion on PR #78
