### ISSUE TITLE
Settings for newly created sessions

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-ietf-webtrans-http2#72]
As an extension or alternative to #71, we might consider HTTP/2 settings that include initial values for WebTransport sessions.  Having non-zero initial values for stream and data limits would improve performance by allowing clients and servers to start sending reliable application data at the same time that they create a session.

The obvious drawback of this approach is that settings apply to connections, whereas the limits in question are resource-based.  That has two aspects: there might be multiple WebTransport resources on the same origin that have different applications and therefore different constraints; and, in deployments where there are intermediaries involved, this requires coordination across multiple connections in order to work effectively, especially if an intermediary serves multiple clients or servers and coalesces requests from more than one peer onto a single connection.  It is possible to present the lowest acceptable value across those supported by resources or remote peers, but establishing what that value is might be operationally challenging.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, this will need WG discussion at IETF 116

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 116, consensus in room was to not use default values and instead communicate numbers. We'll discuss how to communicate this (settings, headers, both, etc.) at a future time.

**Comment by DavidSchinazi** [comment]
Chair: discussed again at IETF 116 at the end of the session. Consensus in room was to not use default values and instead communicate numbers with settings. The setting default value is zero. If an intermediary doesn't know what limits backends accept, it can not send the setting.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, see discussion on PR https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/pull/78
