### ISSUE TITLE
What is the purpose of SETTINGS_ENABLE_WEBTRANSPORT in h2?

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-ietf-webtrans-http2#73]
I can't seem to remember or work out what the purpose of SETTINGS_ENABLE_WEBTRANSPORT is now that we have SETTINGS_WEBTRANSPORT_MAX_SESSIONS. This leads to the following questions:
* If the server sends SETTINGS_WEBTRANSPORT_MAX_SESSIONS>0 but SETTINGS_ENABLE_WEBTRANSPORT=0, what does that mean?
* If the client sends SETTINGS_ENABLE_WEBTRANSPORT=0 but sends a WebTransport request, what is the purpose of having the server fail the request?

**Comment by martinthomson** [comment]
Yeah, I thought that we would remove SETTINGS_ENABLE_WEBTRANSPORT when the session limit was added.  If nothing else, it removes those awkward interactions.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, sounds like we should remove SETTINGS_ENABLE_WEBTRANSPORT. We might add another setting to be removed by the RFC editor for versioning between drafts

**Comment by ekinnear** [comment]
> When an HTTP/2 connection is established, both the client and server have to send a SETTINGS_ENABLE_WEBTRANSPORT setting to indicate that they both support WebTransport over HTTP/2.[¶](https://ietf-wg-webtrans.github.io/draft-webtransport-http2/draft-ietf-webtrans-http2.html#section-2-2)

> The server also needs to send a SETTINGS_WEBTRANSPORT_MAX_SESSIONS setting with a value greater than "0" to indicate the number of concurrent sessions it is willing to receive.[¶](https://ietf-wg-webtrans.github.io/draft-webtransport-http2/draft-ietf-webtrans-http2.html#section-2-3)

IIRC, we discussed at IETF 115 and only the server needed to send MAX_SESSIONS, so we kept both. Can spell that either way though.

**Comment by ekinnear** [comment]
If we're doing this for H2, should we also do it for H3, since we have SETTINGS_MAX_WEBTRANSPORT_SESSIONS there, too?

**Comment by DavidSchinazi** [comment]
* h3 requires SETTINGS_ENABLE_WEBTRANSPORT because it changes the format of server-initiated bidi streams
* h2 has no such requirement for a setting
