### ISSUE TITLE
"MUST reply to the CONNECT request with a status code 426" is inconsistent with HTTP/3

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http2#83]
I don't think the answer matters much but the inconsistency sticks out. Or perhaps its intentional?

In H3 we say "MUST reset all of the CONNECT streams it is not willing to process with the HTTP_REQUEST_REJECTED status " and later on that actually a server could use "HTTP status code 429".

In H2 we say only "MUST reply to the CONNECT request with a status code 426, indicating that the client attempted to open too many sessions.". HTTP/2's REFUSED_STREAM is pretty close to H3's HTTP_REQUEST_REJECTED if we wanted to recommend that.

**Comment by LPardue** [comment]
Also a 426 is [Upgrade Required](https://www.rfc-editor.org/rfc/rfc9110.html#name-426-upgrade-required), so I'm not sure if that's a typo, Seems odd if intentional.

**Comment by ekinnear** [comment]
426 -> 429, whoops

That said, we may also want to make it consistent with HTTP/3
