### ISSUE TITLE
Can we really leave out final size from reset stream?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http2#87]
A question was raised about the following sentence: 

> Unlike the equivalent QUIC frame, this capsule does not include a Final Size field. In-order delivery of [WT_STREAM](https://www.ietf.org/archive/id/draft-ietf-webtrans-http2-06.html#WT_STREAM) capsules ensures that the amount of session-level flow control consumed by a stream is always known by both endpoints.

While in order delivery does help, does it really cover all of the cases for data that may already have been in flight?

**Comment by DavidSchinazi** [comment]
Discussed at editor's meeting: plan is to discuss at 117. @ekinnear can you make slides please?

**Comment by DavidSchinazi** [comment]
Chair: discussed at 117. Consensus in room to keep the capsule as-is without Final Size

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Closing without action as no one has objected since 117.
