### ISSUE TITLE
Flow control terminology updates

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http2#88]
We should clarify: 

- You cannot lower the max number of sessions after the fact
- Stream limits are cumulative, perhaps with an example, saying that you need to keep updating with a higher value if you want more streams (i.e. they are not about the concurrent number of streams)

**Comment by DavidSchinazi** [comment]
Chair: discussed at 117. Consensus in room that this editorial clarification is a good idea
