### ISSUE TITLE
Renumber setting identifiers

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http2#89]
Are setting values 32 bits or 16 bits?

**Comment by martinthomson** [comment]
Identifiers are 16, values are 32.  Issue or question?

**Comment by martinthomson** [comment]
Which leads me to realize that all the settings in the draft are impossible: 0x2b603743 is not something that fits in a 16 bit field.

**Comment by ekinnear** [comment]
Sorry, yes, that was the gist of the issue -- typed on a phone during a face-to-face conversation.

We can just renumber items so that they fit.
