### ISSUE TITLE
Missing CLOSE_WEBTRANSPORT_SESSION equivalent

### ISSUE THREAD

**Issue by martenrichter** [ietf-wg-webtrans/draft-ietf-webtrans-http2#98]
While implementing the protocol, I ran into the issue, that it misses and equivalent of  CLOSE_WEBTRANSPORT_SESSION.
And therefore it is not possible to pass `code` and `reason` in the case the stream is closed. 
`code` is possible using goaway frames, even though this probably has a different counterpart.

Also, I may be missing something, as I am restricted to the http2 api exposed by node.js. But currently, the http/2 implementation behaves differently.

**Comment by ekinnear** [comment]
Looks like this is covered by #95.

**Comment by martenrichter** [comment]
But I was more referring, that I can not transport the reason string over http/2. That is, what I realized while implementing and seeing my unit tests fail, that I looked for the reason.

**Comment by DavidSchinazi** [comment]
Good point, I've added this in https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/95#issuecomment-1885177641
